name: My First Workflow

on:
  push:
    branches: [ "01_DockerTest" ]
  pull_request:
    branches: [ "01_DockerTest" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code repository
        uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t hello-world-nginx:v1 .
      
      - name: Run Docker container
        run: docker run -d -p 8080:80 hello-world-nginx:v1
      
      - name: Test the container
        run: curl http://localhost:8080