name: Kubernetes Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Apply pod to Kubernetes
        run: |
          $content = Get-Content pod.yaml -Raw
          $content = $content -replace '{ID}', '${{ github.run_id }}'
          $content | kubectl apply -f - --validate=false --kubeconfig $env:USERPROFILE\.kube\config

      - name: Check pods
        run: kubectl get pods -n howest-fastapi