name: Kubernetes Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Apply pod to Kubernetes
        run: |
          $content = Get-Content pod.yaml -Raw
          $content = $content -replace '{ID}', '${{ github.run_id }}'
          $content | kubectl apply -f - --validate=false --kubeconfig C:\Users\adria\.kube\config

      - name: Apply deployment
        run: kubectl apply -f deployment.yaml --kubeconfig C:\Users\adria\.kube\config

      - name: Apply service
        run: kubectl apply -f service.yaml --kubeconfig C:\Users\adria\.kube\config

      - name: Rollout deployment
        run: kubectl rollout restart deployment/nginx -n howest-fastapi --kubeconfig C:\Users\adria\.kube\config

      - name: Add Helm repo
        run: helm repo add howest https://howest-mct.github.io/helm-demo

      - name: Helm install
        run: helm upgrade --install nginx-helm howest/example-v2 -n howest-fastapi --kubeconfig C:\Users\adria\.kube\config

      - name: Check pods
        run: kubectl get pods -n howest-fastapi --kubeconfig C:\Users\adria\.kube\config